/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitEntry {
  'id' : bigint,
  'owner' : Principal,
  'createdAt' : Time,
  'visitDate' : bigint,
  'hospitalRs' : bigint,
  'address' : string,
  'patientName' : string,
  'hospitalName' : string,
  'doctorName' : string,
  'medicineRs' : bigint,
  'medicineName' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createVisitEntry' : ActorMethod<
    [string, bigint, string, string, bigint, bigint, string, string],
    bigint
  >,
  'deleteVisitEntry' : ActorMethod<[bigint, string], undefined>,
  'editVisitEntry' : ActorMethod<
    [bigint, string, bigint, string, string, bigint, bigint, string, string],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVisitEntries' : ActorMethod<[], Array<VisitEntry>>,
  'getVisitEntry' : ActorMethod<[bigint], VisitEntry>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];