/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const VisitEntry = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'visitDate' : IDL.Int,
  'hospitalRs' : IDL.Nat,
  'address' : IDL.Text,
  'patientName' : IDL.Text,
  'hospitalName' : IDL.Text,
  'doctorName' : IDL.Text,
  'medicineRs' : IDL.Nat,
  'medicineName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVisitEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteVisitEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'editVisitEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVisitEntries' : IDL.Func([], [IDL.Vec(VisitEntry)], ['query']),
  'getVisitEntry' : IDL.Func([IDL.Nat], [VisitEntry], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const VisitEntry = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'visitDate' : IDL.Int,
    'hospitalRs' : IDL.Nat,
    'address' : IDL.Text,
    'patientName' : IDL.Text,
    'hospitalName' : IDL.Text,
    'doctorName' : IDL.Text,
    'medicineRs' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVisitEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteVisitEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'editVisitEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVisitEntries' : IDL.Func([], [IDL.Vec(VisitEntry)], ['query']),
    'getVisitEntry' : IDL.Func([IDL.Nat], [VisitEntry], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };